name: nixos
favicon: null
layout_spectrum: 0.4885
typography_spectrum: 0.8003783172462136
title: Installing NIXOS on Macbook Air 2011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ebae4'
    - '#5277c3'
    - '#0000ff'
    - '#00ffff'
    - '#000000'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.8624311634339392
purpose: []
